---
language: ruby
rvm:
- 1.9.3
before_script:
- git remote set-url origin $REPO.git
- git config --global user.email "phatograph@gmail.com"
- git config --global user.name "Phat Wangrungarun (via TravisCI)"
- echo -n $id_rsa_{00..32} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- bundle exec rake deploy
env:
  global:
  - REPO="git@github.com:phatograph/blog"
  - secure: ! 'mSsDSrBkW/btd65m49YwAvwAJ+gICInnHv7GWri2bZSKfkn9B/4lN7AAyqaz

      FuU08zND6RpWNBLfd/DlKsIC/fGGGa2O8bCjOjt5eCpMlgaBppjX1aFndLfN

      mTQO7UWu8LTwy4wbRLzcemfYQcMhrYryK7gM14ZDs11+ToxR5vw='
  - secure: ! 'h9F71kVLoBxhIsCmYn/nv8VM8XEw63R80WOo8QgcfE5zAHAF/RuAyiuOfyVQ

      1wbNDUX3Pk7pWjwB7v25CkdZW24Cx7W7GladaFNQuTkXWtArFj6JCgez/pZT

      8D7pBTGEbFtYS6UAKj1Y2do/tSJwKvWhuqBku/32163E5VEmk84='
  - secure: ! 'ce3QYE/FCvMX/mOeVbQ4W/TEn0pxFdtvzZPpKBqi4ifBaY3Hzxm1VI+bN4Wd

      LBSmCV1c9eGXmhPvl8IXxw0cUd4aUSREa9qoNFqfUP9vsw6QEPgWV6aTqan1

      salab2tA3vJrrXb/4J4s+NTYijVnGD6JqPmKJ67L7IQ+wr3Ak9k='
  - secure: ! 'd6lv32C9KbW+e31rPzfe6t7kd5z38gKwNmX+PtuM2wYIhok2hfiIy+umZAmN

      eqlIQ/6DhV2znrysmHAdM5CPNAfSH/rtaw6ojXHaj0rg+Wmr1UkMEud8Uluu

      YL9o1eOElgvviU9pcJVyaAt1bHXuWufzrqkeK0LR4AJaRri1r3s='
  - secure: ! 'amHRor310cPqQyYfkKwxlnBNKuhjkEsqPlMF1ImEctLbWNg98SrDf2s3os8Q

      LPT9Y+0H/cN08xjuwoob63JK1oD6OPU9qj+cfyZKTg1fQPs2Mf1y1djLcOYu

      ikInbxb7Hhqgs5NG9/+je5jtUq+qmQSXmPxcz0gGy/pzbcqNSv8='
  - secure: ! 'EGTbo95NdUEZOXysUXlbFCul5ZLL/KQvAZWNnMJTpaFsAPsBn+3d2+sFvTbG

      Te2fhEKcpNXAWtiKttbFDQ9n4jDqWUm/hJItDtvWoVPPVuxRbMe1H5zpbnNp

      FqznzY8sPH8KhORd1Mcq7iD5iR+Deb2Np9KHEY10b1/6fQUliWo='
  - secure: ! 'DRNNaj3zo3UOgrBTWUTo1rk04kDy8BAIv8XqsrP15s4wdqxrSDE7WMQXDL0p

      RY9b7lpnlULNTJ2rPJDS2F/C4cnzSq26XS+fY54j8ZMdZffK++ZsFfhaD1DH

      HgA4Ui/oZjo/dp1PqHvFOCMESmIv2BTLRCMqp5sv4Z465CUdqBQ='
  - secure: ! 'd9xYk3Vf8h9SerEWxYWwRU6fQYuiJEh5/SIA18WPRn90kOSXzBj/4LaiVPWc

      cg/aUuI5xDYCt/uk+LS6+bfArSjecU7BCY4HtEuGV0B736JJLD/HCNs8rSzD

      wO9HXO9v4UNzFZJZA7r6hQmWgbAQ8eefeajG1BeDDizrHu60x7I='
  - secure: ! 'mi0aFzS0pgQI88AHoTG/Oq156oWEJdUtHMOChtDbWEAEvRh6izDj08kkI3RO

      WpVAfTemloI84fRS+Y4MCEsyjYJUuvvSgL/GiHI0A5n17SK+ziygBbats/rg

      kzuht5kFm9fLRW9tZRAwkLAtPCwD7t/0zNdSyuK/mxjakMnogXA='
  - secure: ! 'mC7esI9wVTdyY+blPYNSzgxzWbiDyLzIgjk/7nOfwYazq/s5OsbgdDUr0y0N

      f8ScAGFJgxHrtDxFm1HK4/NYUTLZFQiE9blm59aAeIPJ8V1Prb6TL7HK7xsJ

      xPoz1zbzK4A4jvuDbTIvopt6LXj5CegwctpMSQ18CGgR2VeCeg4='
  - secure: ! 'Ezh1AQdwn3vb7KoU3yqzIULvj0TsNlFfzZsXczPEVQS6S1VgB+WFZidUpXck

      XuXCesNrgwO+s4CV+OnjqhuFIx4Z2PoyuQ64zY0580uij4RnutTE9g6kCAyo

      bgq4HOl7NUoKnTxwGgh+/qg4f01SMg9hU5su1LGoKDsVQifkv+s='
  - secure: ! 'W3Meb/XBUA+G74pn2fpsrZI/62VMjXhohH8QDoiwTK5AeWoR/xY2PYCITU0E

      OydgYeqN2b9t242c//9fwITEYMPecrsgVaneoefjq/NU5Nr+pBc+zWK+xYT+

      inWZOh1HETORxKsyERV4PJggnJ7zVfmQcsAlHZoHBUdGLuJ5EmQ='
  - secure: ! 'fkY+iAHOAaLLjDX7JTGN5+rBdiFtYwOOnLaG13OZyq6jxFRz7PnrqB8Ss69r

      pwndDDgIvFcZ1JQxDpFzobTJFRdFRvGk+ZTxPZIfwK+tGi5N5tOGD7Wm48s1

      dXpNAxF5Byaoerkbd6Lrzo6LWW8R2qtBKRU4Liu8uAA90M6fa0A='
  - secure: ! 'lEwdQ5R0HM6RAS40gnOX4L8nizMt4ea87LW6kQl7LtBz6tcub83dHYSIehqP

      HGD1QiRDC8gZ1+iMFgmU1MKS6ruoiS/xy5OCAFaUoS7GPQejVtbC3hOYqq5z

      ReGTRtlkKWKbxNkgueTaRNfzFPlm8QK6egIAyG/5v7g08i8zdOM='
  - secure: ! 'np8tGMlb4oGnW9kZwPv/QQgH32pxrxIeG5LI1MK+RXpmHwl+eSpypaafjNcq

      KEatktIXH5nunYrOQ5Gi6Z8+PEWEVKW+0+T7bG3AWKVJ/PkMjlNBHNDrqp2b

      hgQ1XNebCwZfHnMsgtgU7ZRdiys+wL+w/hVcBvmL2sg+pwfEAoU='
  - secure: ! 'ZNVMvTGqedPNI4gvgx23Cl+pSlcFFEZCs8N4FHKilG5526rdGx0eHnMoD54v

      LsjQPvzUkG0P9mXy8cfIecAFv1XAUOWCYWmBrpGxcNIaaUJOO3tKilJxoZEh

      GwAywu2JPKF3zV6xQ2TtnQWUVdBPAMlFY//Us1sg8iYT78v3kIg='
  - secure: ! 'h/DD1KPnMXv4h9LdTo62gIWpnNFoIgyQsPoLH8J55p+5eUWcVrhmGKMPlFwc

      pe+usGkXm4/30/y/BdpgJI5zE2hG4oCuBFXeBC+kDfgX1sVHx39pL23oZMtg

      Xr3R1YWY6PABp4TCCSSolfGAUKvHj9ShZhRBcxSc5iQHWlME6yM='
  - secure: ! 'd8gPLfPxvhW9PiUSVDvK+sh+hwORDs1vlOO/VFCB8XIGz9OQXTyGs784YiYf

      UW7ynnx3gITpgDyMDH2EsSa/bgompgck4t7ztADwp7ZSJSD9/nQK+zNasVGI

      zAYHTUQt/aojyWLfH9xxnJqM3yIUrMHBcNAtcWO46bnZyfDLkhI='
  - secure: ! 'c/BvM+K6ccA5Bo5b5Yz4UAIIThDcYGWJ6F9I6tIuJvNTOxlc6Cl6QFjr0Umd

      gV+R6ieMvXNr3gzTQ3NSu2wzLQSXe8t9WQbPw28zrFtIb8k5jWx4aeahROCY

      IXHlXu5MFDSJ/TawUIBc9glkDqYnH19ttpeGqNd6aBmFI1fcN8I='
  - secure: ! 'cvFshbJTWNi8P5W6ZxUBr71iWA5gTAQzA32d/w75AFb/mYJFMUu3CF3kaiGK

      OZ+QFmnpfxOVdEQJS+Iq2bgSpuwVatlS2J5KnyJin08rOhFDDJj/TfN9ew9M

      IWk8IFgIW2nMbcW3Kgy/g5BpIqJgSSWPJu33lI1IJ/ZQboKZ3jU='
  - secure: ! 'CRyZMBIkoYG3Rn+vu12+5GehqG2Gox3PJFmOioixnCPEU106EesNruFcKRCQ

      HeNjTy/CXM7bTbm+jpVjrY0HYiviBLF6InDU97xH0+amuwe4h+HLLsNC53Qa

      mIoQDFeJfXpw+QhdamFk1lDLl5pES/X8i863yn5jd7uPf1PCI24='
  - secure: ! 'khCIH12mk48AHCKuRahsuZ4o0URqGnuRl6PY7IWHotvQC1znkeimi19btDcN

      BICo53Pf0TZBuqyXroB5oYm+51sP1S3+sK2FpjPN2HSWd3v/rFRd1K2bVRGW

      bPT1Caau2TgJTxnBt3izxVfv9D5aXR4o0quM9y0YcnJAWov3A0g='
  - secure: ! 'Deh7XmIz7dT0PMugRhLqufrOmbBn4eaHRMJM8sRAcYkaP6qg5Jr7n4kkT5fc

      w9/88aMGMvq7t8TiJfimCkkrmcsl30KAZsWWbn5SNqjR7VH3VLt1LrB2GBAu

      V60JLqOoOlZCcEv70ptj/Td8+PSb15fUxJDPt+OPiHPzN8fliY0='
  - secure: ! 'gkX97yb1A4WIl8/x/Z7cB/PCOaMtMmHUC6hEsxRrzj98KyE6rNvoM4rr42Iy

      2H+d5z3fzXRhfTRKOt7QGPC7tX8qqlvBFrdK71kqhv1e5BfpzW0dg2WK7YoS

      ACOo14luIkJOUrOELhQPszrxVl/c+cf1ecpnEMTAuVQr6cvgy1o='
  - secure: ! 'JRQJR4Cbq/wmsYtJhRe1HlwZ3MVdlXux8waF2c4QHP5kXfmrhan6+QH0j/HT

      UFOfMoU3TohFpPTFll14hDCIgw+R1O77kICzm2CaX0AIM7ADZBET83gLqxpL

      vEEuuXOYuEy+D2WcqSDUAX/OTHvfceBQJAM9AA147W+ewg4LeFA='
  - secure: ! 'Mv17Bvds1PZPZB0g7k74UMIqwW1VnLnL2xK3WSj8cX+OTMfuQcVOrREKDO0h

      Yom/Y9TfJjAUZ7mWgyYjrh1e7aDSegSmBNvO6s/FTETeU25k3Xz8gLjB5h+k

      y5bn1R/vSEe1EzTWoHPyIXDreEA1HQ26hRAWggPUAXX555rKlbc='
  - secure: ! 'bRBKF9MCbGTiWPSVmZv7KXXSIUApd2SHlDzBAYgL+YvijZr6F9qjJJOyoyC5

      Li9eunnqON7cdilYDWtqllTeBUS1vI/iC1spg3bexBsob0xNrn+zSBqia4tc

      99brXYLSfXAHKkAe86iLViQzb5P3072n2K70SLfpftDt09b7KYM='
  - secure: ! 'i4MvteGxJC7i1sYbCjze3MF1/geswtyGBQSuSNSWaDmpAEh85pB1I1E7I17B

      UF8+ZkLP74Jb90J0EFuHR4ZCt8+6+hptKP0FpE0mBwrDBoL5eeEih73fJqSP

      ck+f3l2jOS7q3bRxyb84/YZXMyh0QLe49BBSMiDQgnUCCthh57Y='
  - secure: ! 'OSOJRxGTfBRo3uFyaDF4ayhg2JLvPkBcOUESaH/qPjuea0Ww/IVbQJTnKw/n

      JFQ2406SWLiYbDAFOnv4qsz4jbCN+a6UyjO5pys8SsC9HtpDy/eSxY6ztxp3

      Iczarya1oMF+Agq0YW5EDq28tOw99iJWpezcsk0tcv1fqV9Y7tc='
  - secure: ! 'PbShLQls1+pgpD1XSw4Mh0w6tllAGqpzDOsaRQ0oq+aJKQc3g0yghugCojWj

      ReERcvRkxWL4zkrAEv5qwx+fQg0n5W3HP0ZfygOJP622S020d5l0i4FAoGud

      meHoO4i6u+AuDN612IZx/zBLNv/Xrg6uhDaCjLXnnoKauPRscqU='
  - secure: ! 'M02tDqpZ3HBt0GBe2bz9rEkWsMcFKtZ022hna/nWWM2r7rbi8otB+D1XEjzT

      AOwbnEZmza8RMdeLDB8+QNEPmn5Fmpa5UTYoRjvgOhgC67qJUEXfsiQwVxuC

      qJhjcUAWAGzIoGkYym1/wFSrS4NUg/Qb4heVN1WXbR7S275pRJQ='
  - secure: ! 'AoiXmN1y4tO3Ii768EPStnFISEWDNSl4OFHaftb5wuTVHj9vHKNl3hktdIc5

      Y44jHOSCzkfrmpDiO/88CVBMMNZfTp1AMQQ+mmPxDJdNsJstQgwlEkrUlt2I

      Q3cIMjwItBHYrUOA2nPg2tyzdnGcKvSellXIxgPpCwb0LhTqlTM='
