---
language: ruby
rvm:
- 1.9.3
before_script:
- git remote set-url origin $REPO.git
- git config --global user.email "phatograph@gmail.com"
- git config --global user.name "Phat Wangrungarun (via TravisCI)"
- echo -n $id_rsa_{00..32} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- bundle exec rake deploy
env:
  global:
  - REPO="git@github.com:phatograph/blog"
  - secure: ! 'V/CI0NZuxPoJwMujn9d5ZADtFcbcQtRipB2XPL5U41bMjtGsMa1iiwR0Fd5H

      cpjFQsqlDWwdHkewJY/5PFrGxWX/+TNwHEado4GDi5MqIognU1TPGDO31T+I

      3Pz5Nqq2gSvzkfM4Y2hJ6rMQpvqXHy8ICqf1Pl+7TMSsaJ9ex18='
  - secure: ! 'cUGqWSM8ilzi0jN5SUwP/jGbnpL98nXUpkUGVa/FJsAAmLARp89gjTNaoaLM

      We+BS6d2C3SDdjs/uUMHeJsGjVJUK35Erz4oSAiESrk4cVyqhCoeK2a0joGp

      n7i3Ne9hnS8j8dBcbeBcwVSjgDbCt4emy094DVWJ14tYk7AXVh4='
  - secure: ! 'kYZCwt2JFFTEuNyCV9B1GA2OEajrs5ZnGKAifEdPlOCCJnPAA0Wz0aF2kBms

      6PZ2/BQ0FKj/Iiz59QnXJMPGvOoJxUcMNVaEm6LiBFqMw2xzEHeYBi33VMfH

      xbLS3g2qqaaWg6Vzb99T/VMfZJIC5nF2c1hAJxXChl4WirVaIOE='
  - secure: ! 'hkzEityIg9SvxeHEWppKC8Pzt6CL5xxAtOp9GREkHNwsJaAylYD/VyRMKpYi

      nDAuZLpqk67Rz/RVGEehcnldB54N/JpitWSy1jxycD9eK/cHk+uaMseGdCVU

      JdbS4diIIec5qONVEzm2x0ImWb6B1czj+jjRdygXqNXUE2AKF9w='
  - secure: ! 'aMfu8FKHSRKbK82G06gDgE2VET4Nej7vIxs2J1xdiJoyzfxY4YawnL/dWkqO

      3VC/pXKGTQQpyy0XivTpio6XRU9VLM1VsggHiBIyky82DlEDx8p3+sewbjVi

      ZCzbjpGgJeEEqcvEQ2jOg4Elzw36KpxATqKZ7eNqpJhJByju51k='
  - secure: ! 'BuYRp+c6B1PRzjnZB9DCUrJ0cFk2rGUs0rVwvsrhrxnc/Ihz6oYy0MB9Vkkm

      tA6lOf4+kbDkjh3TN/4fImcvJ6e1jSsaBwwiX6fRTNPe3hv2TqE0RAw/w1VU

      Wgslj9KNA1qbgYymNVywqIU9uKUY+SXublnwRf8haqgpyMkM1eg='
  - secure: ! 'YbteZ3WQdnbcLjyyvLAWFSbYFWKS3CoVfenoaKT41qkY2q6+oEY8z6rLT3a0

      Nl5uVXv6Et5PcbZul1/+Nt9GOcH7YxgOKeIgQOCxikOjgKePvmMkIpFLbr0T

      9a2k+HevoDRw7tGllhOJoL/NvyyZm1dtUJ2qjylxv6ikIxGshlA='
  - secure: ! 'R3vrsZVRLZwJ6UpjXyuk73/scNVDb4DrBEbha1MBlpr1t9GYzm4t/oGBdL1H

      dOpoekWk6CWWK3sTDjUt6NGvWHiSVpDqQAxesw1fqBlnI9qU9BoMCqOKNFDO

      fjkWSxK/+AHfErwCmfqRcujWSo1xmVQrQFRU+MV+ZWhDm4KNLUI='
  - secure: ! 'nKXPfJbafdnlpKRjn5wNuT2hD2WffaixfLnZU7NLJDKL/knsEzWKQRxO7CdT

      rSXnbFAk52n5iMits4noVdUonpmoSqReyUMD1U/bkohX4PXB9hDS7LVdl5RY

      UmbW/w3PrEXfM5PXwZ8tpEsF6go1zu93PLqCkgUWCYvPv5zfUuQ='
  - secure: ! 'Z4LfmkBLaESGogTcYt2gUfYWicuTy1WXl6lLX74DoT4Wi+3BhXOucRnTWbdj

      LEzCH6YCZu9BksoxPcd7a1SMc3ESKQ80bdKnuC6RMCruQ/np/X+qzPKFmOyE

      gy0Mwr9temYUUzSdnfPfy4xb8GIKYls/ZuFonY0tN+AvtWet22w='
  - secure: ! 'kjc0wuX+1xtxG43HxTdoKWfpC0Sfxc+eVlGklZaeMh+CPz1jjUJ8Hpmh7sy4

      ZKSQYMDVyZzIpdKuIbTrf0vzBPPxLDnopWZCNkspPx9tL9cAJnaT3j71woxR

      wlgcKrqaVIpYjiI23zF7x3ogz1iGZpYkJ+l4dxmH39dINLkDOgg='
  - secure: ! 'hfuz32Adyd07fePA1WY9s3igTEPW2n4Wj1fxInHHBBtEfd/kPwMoR3mnYLBc

      I8xsHBqTFMV13Br45IN4npTf1teIIEb1xQrv2Kb5p2uQjPpVVnAmngEUcygh

      lWu4W8K3io6p6GEYKBshzyR0daxXGpDbD2fy5c5cJpbk48BcscQ='
  - secure: ! 'rkC9OHCE5rlzcUp9AT6q8zi9MuFBVziWXNfVbq00FiYweyKVH440RvOdLRs9

      7wFy750lh3jXvHSDLskZDKofQ1jqJnuLrjOtpUxnl3SQ0gipRjAmqZRvyna/

      loUvXuij/20BHlHpMf3jsvChr7D5b5juOs6oWN8n0PKYBOuBRTM='
  - secure: ! 'fhKQvrWQUYNU5xT0Wz79PyrxIioeUSQ8jvAWh49VVcQAeqxYCeCbQCN4Qpv2

      szUhg2Fd26p9PcT2Q9Y05jFUPtM7D4wl56/Je6XfqNAC+PigTOkfsxtmkuwy

      cVrHs26XE3s1VTQVRfyD3SwJ5EY3cGKBC0OsyF3cD5m7lJVBDuY='
  - secure: ! 'HBO5IdaS1zfJeZ6E2cimyzYr0l2+qzMBKtTqsN2zVJaUDLxJI+LPiG/SHP2Y

      LeLnlmO5TzV9jItceSmxz4lDCVYvaZz36VAgIh5ElseRemgzeTNRPk65/shM

      oLpAUDmxkFxb9nd76vfFCu+QABXjXSLKfbcq8u12A/ebmXA8m6Q='
  - secure: ! 'fy0b3uP935VLzJza+0ANWgX31btnSCFh4Nq+CX2E5mtbsd78xXdC4iCA9BqT

      EwpJEWv0xfrhvmD2FTA0Z/7206gLBGnEbrrFLqMazJ2xDb5nLCq9N7Ka4wjx

      BTcqUKKO1M/gMnGHQtP9pcMY9CugfoA6BvorRO5udSoERoMkqTs='
  - secure: ! 'cNL6kKkc5MTR3J0DafNw59aTECj5svdYBuES3lfIcYggyImI+I2Ay8MSmVON

      wkMHm+3w7I1ft18xdb2S9qQfcDoxm32VGG4JoFfzFyKtaAzN5H615xBgTHw+

      9d6zuDzyFeAkrWWYuJgw5md1FAaDf34fbrArJcNTJzn4Xf3SiRo='
  - secure: ! 'FrHpqhD0avVyvhDyoZm2CwlfhC+bPzOQUB1mhyDmkmxSGo9gONJmpXMtCPE9

      kJRt6zKPRPFBZRtCoui4vdRofOcUOQQTlwI6xUE+9JEG3H/3/tTaNG+NwAGK

      /SqHYtEno+WKykCFY0yxv/oPrK5Q2miPHHN9loaQDO2NeN5Mo0A='
  - secure: ! 'SDcXPZQFFMSqIYG62ihjgDUOsD+sDkymDVe49GcpVFVFb6q4sFE314Gay2In

      YsrtUAzgqApm0VBj3CR36X9AMqEbuEknSLIW3vf6uFhQdUZ9LJmjglY3i0XV

      HheEGZxzTShbf6Mvw4pz2S7WiPwgKt51qQiqIf1/UtX7V2FYiU0='
  - secure: ! 'piiHvyOh5vgg5FIe1KruEBS3a1rceIV/6ebfkgTRE9R2kdw4/DckUjCxR/9G

      2mnir/PApCHOIYRVLKKvhueXLEKseWJKgyfw3m6bsqCitkyYc4XSmLGj4Xgw

      Vr6Pp139b5T7yQkTWxwPJSkHl7RfX89XsKcYOOx+4Va+dOkpbKw='
  - secure: ! 'eddq2PKOmqjfWKs7EF7JhwyofwlzAz87Gem9sYXuUTm0479z19S0rhBzN/D1

      8VpiRgtN/zJVQpvoE0o7X0YZw1vEOARbO9rd3TB+MON0UmQ8JGAmg/JR9AAv

      jEo+tRRcfVfxfzAGzja8KFDY+qXSDI9Rgtuz72sbm19ymNf0R2s='
  - secure: ! 'SEd5wfnXnatm62HD/KSqo6WcItAuoeie9kjq1ope36oG9Yr+lgYAzDZBlryY

      uVI7tVraBeNUXSLP/X9oUJ4M91hUQJsekkzxzDriLz7c8VZ0AHzsPlb00lLI

      5276Oo1uwLD/DLUKVxa3rrb/7M9xzAp829O9KH6/ASRna5h+UIs='
  - secure: ! 'Mx/J3u+fuXOYUI0rWSl53kJxrmA+cXtqYkVMkhk0aGpz5yPqDVou759DHLXH

      7gDPHLWhR7AbddTz2/epCjp4olevdy5SqVi5MAA7cob0ng/n5HuwNJE7Vhlk

      8VJx0lK1xCEd1V54OTuU8A00cOpyx4s2NDaPBnEad0ZrKYgQQfQ='
  - secure: ! 'kcqNhw1+5/xJylaPmI0JFlVPk4t84vdM0YE6qMkvrBzdNPngZf3Nsydr+Bvd

      DB6zDYyQPJv3NyiayYdGAw57kLhPE8sKY4pZeK4vJFB+FYk7XUnpoZ1AXPqD

      PLVEn+I817JF2Oi+Ha5CsIanvOJ/rQ11EvDmvSwwNRWPVRQ2ycM='
  - secure: ! 'diAwoGVuwlPVfL/XR2iif6WcUtkqmoE0lIFVxDy8rwgQPiR82GqLSGMGLwX3

      YqKsx+9zgRJWYtY2uMRFry6ZCQ1R1kBKENGJLtt6gGJuL0wc+sYtUpuH61rR

      htnQdWPQWp1zSyQPErc6IbYeeYQhB5hx5TkSYcwhDsDCYlXaJsY='
  - secure: ! 'diTuhIJkpXv3Y4d5l5K42uTInUMb7B5jvvdtU+dedpVnE0JKtseYStNlfz8N

      WIG0GBZwA6oMYGfOne+w2STGyZ4Bdfbnd3DFUfE/9SxXnjBxC3pqIp9O3pP2

      yVuCuV0PQhdG0YscS07WLy+V15hJIMVzbzu5zhY91j78R2ott2w='
  - secure: ! 'K0hyTH0jA/DKrqmG9KhcCllDcTu+idbd15Dlk3wwwPc3iR8IYBSgXd7v9UNx

      XOKGvqjvFcdtQavJyL7ko8IDk17LUe48pLpS7L8dMZQ9xYaTVMDu9LPgXm65

      2zg0rnxki2sxAxRKDtWajPgCRZdhdPpWWRGShdgRKqmUSnXn8nM='
  - secure: ! 'OMvtQQGV+mTEjrqHSy1MjkhK0u4VtC+OHXAUMB/6KjNZuOW0R6KgQgt8mBZF

      LzNOyMdNvn/jm4Lc95RZsyLFkQwo/Spww/Ki6HQAsGWlQUWZjDVpVVwacFas

      HR+Mnt1W1AP4EwUYrX+tg24rjivZS8wxQmcIavBhaNJpxaYIxn8='
  - secure: ! 'iI4xgchq0R1dD2x7U2RytocHC3ZPf67P7XOOjhFKYn79Jlk98xYnSDSxFOdn

      BXI8pO241Oyv+Vf6ID3tI5tQyjeREkGK14IQqU/DnbecSsMdzP5PRrqS61R8

      j4g0qKNXmlOWhLkDkvZdBxNG2WSLuH5d6E2fqxEwO5Hr4VkRwsg='
  - secure: ! 'Yjty3tPlsPujF1D3ktDxL2r2xcOFNdo1rE7OwLoRypFlVUtK/MP+3vgNxuR0

      E59biTTbCc8tYOBlVQ4SIZcsvw3xjO31/GQeCpWaxJkaZH4/fPvIQ7IjWMfL

      JqFAZeDOPrpVUYeRq7+lGeHLGJNfVAsGdBSOrhDA/1/1UUw55Vw='
