name: phato.blog
baseurl: /
markdown: kramdown
highlighter: rogue
permalink: /post/:year/:month/:day/:title
paginate: 5
paginate_path: /page/:num
gems: [jekyll-paginate]
exclude: [vendor, 'Gemfile', 'Rakefile']
