name: phato.blog
baseurl: /blog
markdown: redcarpet
highlighter: true
permalink: /post/:year/:month/:day/:title
paginate: 5
paginate_path: /page/:num
gems: [coffee-script, sass, jekyll-paginate, redcarpet]
exclude: ['Gemfile', 'Rakefile']
