name: phato.blog
# baseurl: /blog
# destination: ./_site/blog
markdown: redcarpet
pygments: true
permalink: /post/:year/:month/:day/:title
paginate: 5
paginate_path: /page/:num
exclude: ['Gemfile', 'Rakefile']
